import { ArtistProfile, WriterProfile } from "./types";

export const MOCK_ARTISTS: ArtistProfile[] = [
  {
    id: "1",
    username: "yuna_draws",
    display_name: "Yuna Kim",
    role: "artist",
    bio: "Manhwa artist specializing in romance and fantasy. 5+ years of webtoon experience. Open to long-term collaborations.",
    avatar_url: null,
    banner_url: null,
    location: "Seoul, KR",
    website: "https://yunadraws.art",
    created_at: "2024-01-15T00:00:00Z",
    updated_at: "2024-01-15T00:00:00Z",
    art_styles: ["manhwa", "webtoon"],
    work_types: ["commissioned", "contracted"],
    availability: "available",
    price_range_min: 50,
    price_range_max: 200,
    portfolio_items: [],
    genres: ["Romance", "Fantasy", "Slice of Life"],
    languages: ["Korean", "English"],
  },
  {
    id: "2",
    username: "inkmaster_ren",
    display_name: "Ren Tanaka",
    role: "artist",
    bio: "Manga artist with a focus on action and sci-fi. Clean line work and dynamic panel compositions.",
    avatar_url: null,
    banner_url: null,
    location: "Tokyo, JP",
    website: null,
    created_at: "2024-02-01T00:00:00Z",
    updated_at: "2024-02-01T00:00:00Z",
    art_styles: ["manga"],
    work_types: ["free", "commissioned"],
    availability: "available",
    price_range_min: 30,
    price_range_max: 150,
    portfolio_items: [],
    genres: ["Action", "Sci-Fi", "Thriller"],
    languages: ["Japanese", "English"],
  },
  {
    id: "3",
    username: "wuxia_pen",
    display_name: "Li Mei",
    role: "artist",
    bio: "Manhua artist passionate about historical fiction and wuxia stories. Detailed backgrounds and expressive characters.",
    avatar_url: null,
    banner_url: null,
    location: "Chengdu, CN",
    website: null,
    created_at: "2024-03-10T00:00:00Z",
    updated_at: "2024-03-10T00:00:00Z",
    art_styles: ["manhua"],
    work_types: ["contracted"],
    availability: "busy",
    price_range_min: 100,
    price_range_max: 500,
    portfolio_items: [],
    genres: ["Historical", "Fantasy", "Action"],
    languages: ["Chinese", "English"],
  },
  {
    id: "4",
    username: "sketchstorm",
    display_name: "Amara Osei",
    role: "artist",
    bio: "Self-taught comic artist blending Western and manhwa styles. Love dark fantasy and horror stories.",
    avatar_url: null,
    banner_url: null,
    location: "Lagos, NG",
    website: null,
    created_at: "2024-04-05T00:00:00Z",
    updated_at: "2024-04-05T00:00:00Z",
    art_styles: ["manhwa", "comic"],
    work_types: ["free", "commissioned"],
    availability: "available",
    price_range_min: 20,
    price_range_max: 100,
    portfolio_items: [],
    genres: ["Horror", "Dark Fantasy", "Action"],
    languages: ["English"],
  },
  {
    id: "5",
    username: "sakura_lines",
    display_name: "Hana Mori",
    role: "artist",
    bio: "Specializing in soft, emotional manga artwork. Perfect for romance, slice-of-life, and coming-of-age stories.",
    avatar_url: null,
    banner_url: null,
    location: "Osaka, JP",
    website: "https://sakuralines.jp",
    created_at: "2024-01-28T00:00:00Z",
    updated_at: "2024-01-28T00:00:00Z",
    art_styles: ["manga"],
    work_types: ["free", "commissioned"],
    availability: "available",
    price_range_min: 40,
    price_range_max: 180,
    portfolio_items: [],
    genres: ["Romance", "Slice of Life", "Coming of Age"],
    languages: ["Japanese", "English"],
  },
  {
    id: "6",
    username: "cyberbrush",
    display_name: "Jin Park",
    role: "artist",
    bio: "Webtoon veteran with 200+ episodes published. Cyberpunk and dystopian fiction are my home.",
    avatar_url: null,
    banner_url: null,
    location: "Busan, KR",
    website: null,
    created_at: "2023-11-20T00:00:00Z",
    updated_at: "2023-11-20T00:00:00Z",
    art_styles: ["manhwa", "webtoon"],
    work_types: ["contracted"],
    availability: "closed",
    price_range_min: 300,
    price_range_max: 1000,
    portfolio_items: [],
    genres: ["Sci-Fi", "Cyberpunk", "Dystopian"],
    languages: ["Korean", "English"],
  },
  {
    id: "7",
    username: "nova_strokes",
    display_name: "Sofia Reyes",
    role: "artist",
    bio: "Freelance comic artist from Mexico. Bright colors, expressive faces, and tight storytelling.",
    avatar_url: null,
    banner_url: null,
    location: "Mexico City, MX",
    website: null,
    created_at: "2024-05-01T00:00:00Z",
    updated_at: "2024-05-01T00:00:00Z",
    art_styles: ["comic", "manhwa"],
    work_types: ["free", "commissioned"],
    availability: "available",
    price_range_min: 25,
    price_range_max: 120,
    portfolio_items: [],
    genres: ["Fantasy", "Adventure", "Comedy"],
    languages: ["Spanish", "English"],
  },
  {
    id: "8",
    username: "dragonquill",
    display_name: "Wei Chen",
    role: "artist",
    bio: "Manhua and manga hybrid artist. Loves epic fantasy sagas and world-building-heavy stories.",
    avatar_url: null,
    banner_url: null,
    location: "Shanghai, CN",
    website: null,
    created_at: "2024-02-14T00:00:00Z",
    updated_at: "2024-02-14T00:00:00Z",
    art_styles: ["manhua", "manga"],
    work_types: ["commissioned", "contracted"],
    availability: "available",
    price_range_min: 80,
    price_range_max: 400,
    portfolio_items: [],
    genres: ["Fantasy", "Xianxia", "Action"],
    languages: ["Chinese", "English"],
  },
];

export const MOCK_WRITERS: WriterProfile[] = [
  {
    id: "w1",
    username: "stormscribe",
    display_name: "Elara Voss",
    role: "writer",
    bio: "Fantasy and sci-fi writer with three completed novel manuscripts. Now looking to bring my stories to life as a manhwa series. I write detailed scripts with panel breakdowns.",
    avatar_url: null,
    banner_url: null,
    location: "Berlin, DE",
    website: "https://elaravoss.com",
    created_at: "2024-03-01T00:00:00Z",
    updated_at: "2024-03-01T00:00:00Z",
    genres: ["Fantasy", "Sci-Fi", "Adventure"],
    looking_for: ["manhwa", "manga"],
    projects: [
      {
        id: "p1",
        writer_id: "w1",
        title: "The Shattered Crown",
        description:
          "A young thief discovers she's the last heir to a cursed bloodline — and the only one who can stop an immortal king from rewriting history. Epic fantasy with political intrigue, magic systems, and a morally grey cast. Script is complete for the first 12 chapters.",
        genre: "Fantasy",
        style_wanted: ["manhwa", "manga"],
        work_type: "contracted",
        status: "open",
        created_at: "2024-05-10T00:00:00Z",
      },
      {
        id: "p2",
        writer_id: "w1",
        title: "Echoes of the Void",
        description:
          "A short sci-fi one-shot (20 pages) about the last surviving AI aboard a dead generation ship. Looking for an artist to collaborate on a submission to an indie anthology. Free collab — rights shared equally.",
        genre: "Sci-Fi",
        style_wanted: ["manga", "manhwa"],
        work_type: "free",
        status: "open",
        created_at: "2024-06-01T00:00:00Z",
      },
    ],
  },
  {
    id: "w2",
    username: "romanceweaver",
    display_name: "Aiko Sato",
    role: "writer",
    bio: "Romance novelist turning to webtoons. I write character-driven stories about love, identity, and self-discovery. My scripts are detailed with emotion notes for each panel.",
    avatar_url: null,
    banner_url: null,
    location: "Toronto, CA",
    website: null,
    created_at: "2024-01-20T00:00:00Z",
    updated_at: "2024-01-20T00:00:00Z",
    genres: ["Romance", "Slice of Life", "Coming of Age"],
    looking_for: ["manhwa", "webtoon"],
    projects: [
      {
        id: "p3",
        writer_id: "w2",
        title: "When the Rain Clears",
        description:
          "A slow-burn romance between two university students — one dealing with grief, the other with family pressure. Slice-of-life manhwa style. Looking for a long-term artist partner for a 60+ chapter run. Budget available for serious applicants.",
        genre: "Romance",
        style_wanted: ["manhwa", "webtoon"],
        work_type: "contracted",
        status: "open",
        created_at: "2024-04-15T00:00:00Z",
      },
    ],
  },
  {
    id: "w3",
    username: "inkblade_kai",
    display_name: "Kai Oduya",
    role: "writer",
    bio: "Action and thriller writer. Former comic script writer for two indie publishers. I know how to write for the page — tight dialogue, clear panel direction, and kinetic action sequences.",
    avatar_url: null,
    banner_url: null,
    location: "London, UK",
    website: "https://kaioduya.co.uk",
    created_at: "2023-12-10T00:00:00Z",
    updated_at: "2023-12-10T00:00:00Z",
    genres: ["Action", "Thriller", "Crime"],
    looking_for: ["manga", "manhwa", "comic"],
    projects: [
      {
        id: "p4",
        writer_id: "w3",
        title: "Blacksite",
        description:
          "A disgraced special forces operative goes rogue after discovering her last mission was a government cover-up. Gritty, fast-paced thriller manga. 5-chapter pilot script ready. Commissioned artist preferred with credit on publication.",
        genre: "Thriller",
        style_wanted: ["manga", "manhwa"],
        work_type: "commissioned",
        status: "open",
        created_at: "2024-05-20T00:00:00Z",
      },
      {
        id: "p5",
        writer_id: "w3",
        title: "Street Kings",
        description:
          "Urban crime drama following rival street gangs in a fictional African megacity. Heavy world-building, ensemble cast. Looking for an artist who can do expressive urban environments. Open to free collab with revenue share on publication.",
        genre: "Crime",
        style_wanted: ["manhwa", "comic"],
        work_type: "free",
        status: "open",
        created_at: "2024-06-10T00:00:00Z",
      },
    ],
  },
  {
    id: "w4",
    username: "xianxia_dreams",
    display_name: "Mei Ling Wu",
    role: "writer",
    bio: "Wuxia and xianxia storyteller raised on Jin Yong novels. Writing stories that blend classic cultivation arcs with modern narrative pacing. Looking for manhua artists who understand the aesthetic deeply.",
    avatar_url: null,
    banner_url: null,
    location: "Taipei, TW",
    website: null,
    created_at: "2024-02-28T00:00:00Z",
    updated_at: "2024-02-28T00:00:00Z",
    genres: ["Xianxia", "Wuxia", "Fantasy"],
    looking_for: ["manhua", "manga"],
    projects: [
      {
        id: "p6",
        writer_id: "w4",
        title: "Heaven-Defying Sword Saint",
        description:
          "A disgraced sword cultivator must climb the heavenly ranks once more after being reincarnated in his own past. Classic xianxia beats with a modern twist on revenge arcs. Script for first 20 chapters complete. Long-term contract preferred.",
        genre: "Xianxia",
        style_wanted: ["manhua"],
        work_type: "contracted",
        status: "open",
        created_at: "2024-03-15T00:00:00Z",
      },
    ],
  },
  {
    id: "w5",
    username: "horrorhaus",
    display_name: "Dmitri Volkov",
    role: "writer",
    bio: "Horror and dark fantasy writer. Published in three short fiction anthologies. My scripts lean into psychological dread and unsettling imagery — I want an artist who isn't afraid of the dark.",
    avatar_url: null,
    banner_url: null,
    location: "Warsaw, PL",
    website: null,
    created_at: "2024-04-01T00:00:00Z",
    updated_at: "2024-04-01T00:00:00Z",
    genres: ["Horror", "Dark Fantasy", "Psychological"],
    looking_for: ["manga", "manhwa", "comic"],
    projects: [
      {
        id: "p7",
        writer_id: "w5",
        title: "The Last Parish",
        description:
          "A small town priest starts receiving confessions from people who are already dead. Slow-burn horror manga with strong atmosphere. One-shot pilot (30 pages) scripted. Free collab to start, paid for ongoing chapters if it resonates.",
        genre: "Horror",
        style_wanted: ["manga", "manhwa"],
        work_type: "free",
        status: "open",
        created_at: "2024-06-05T00:00:00Z",
      },
    ],
  },
  {
    id: "w6",
    username: "comedyquill",
    display_name: "Priya Nair",
    role: "writer",
    bio: "Comedy and slice-of-life writer. I make people laugh through characters who feel genuinely real. Obsessed with perfect comedic timing in panel layouts.",
    avatar_url: null,
    banner_url: null,
    location: "Mumbai, IN",
    website: "https://priyanair.in",
    created_at: "2024-05-15T00:00:00Z",
    updated_at: "2024-05-15T00:00:00Z",
    genres: ["Comedy", "Slice of Life", "Romance"],
    looking_for: ["manhwa", "manga", "webtoon"],
    projects: [
      {
        id: "p8",
        writer_id: "w6",
        title: "Absolutely Terrible Flatmates",
        description:
          "Four completely incompatible people share an apartment in Mumbai. Chaos ensues. A comedy slice-of-life webtoon in the style of light manhwa. Looking for an artist who can draw expressive reactions and comedic timing. Paid commission for chapters.",
        genre: "Comedy",
        style_wanted: ["manhwa", "webtoon"],
        work_type: "commissioned",
        status: "open",
        created_at: "2024-06-15T00:00:00Z",
      },
    ],
  },
];
